default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy (warn-only)
        entry: bash -c 'mypy TikTokLive || true'
        language: system
        types: [python]
        pass_filenames: false
        verbose: true
        stages: [pre-commit, pre-push]
