# Generated by the TikTokLive compiler.
# DO NOT EDIT!
# SERIOUSLY!
# I MEAN IT!

from typing import Dict, Optional, Type, Union

import betterproto

from .base_event import BaseEvent
from TikTokLive.proto import *  # noqa: F401,F403



class BarrageEvent(BaseEvent, WebcastBarrageMessage):
    """BarrageEvent."""


class CaptionEvent(BaseEvent, WebcastCaptionMessage):
    """CaptionEvent."""


class CommentEvent(BaseEvent, WebcastChatMessage):
    """CommentEvent."""
    user: ExtendedUser
    at_user: ExtendedUser

    @property
    def user_is_super_fan(self) -> bool:
        """
        Return whether the user is a TikTok super fan.
        """
        return self.user_identity.is_subscriber_of_anchor


class ControlEvent(BaseEvent, WebcastControlMessage):
    """ControlEvent."""
    action: ControlAction = betterproto.enum_field(2)


class EmoteChatEvent(BaseEvent, WebcastEmoteChatMessage):
    """EmoteChatEvent."""
    user: ExtendedUser


class EnvelopeEvent(BaseEvent, WebcastEnvelopeMessage):
    """EnvelopeEvent."""


class GiftEvent(BaseEvent, WebcastGiftMessage):
    """GiftEvent."""
    user: ExtendedUser
    gift_details: ExtendedGift
    to_user: ExtendedUser

    @property
    def user_is_super_fan(self) -> bool:
        """
        Return whether the user is a TikTok super fan.
        """
        return self.user_identity.is_subscriber_of_anchor

    @property
    def gift(self) -> Gift:
        """
        Convenience accessor for the gift definition. v2 exposes it as
        ``gift_details``; we keep ``gift`` for ergonomics.
        """
        return self.gift_details

    @property
    def streaking(self) -> bool:
        """
        Whether the user is currently engaged in a streak. False for
        non-streakable gifts; otherwise the inverse of ``repeat_end``.
        """
        if not self.gift.streakable:
            return False
        return not bool(self.repeat_end)

    @property
    def value(self) -> Optional[float]:
        """
        USD value of this gift event. Returns None mid-streak so callers
        do not double-count; the final non-streaking event carries the
        full repeat_count.
        """
        if self.streaking:
            return None
        return self.repeat_count * self.gift.diamond_count * 0.005


class GoalUpdateEvent(BaseEvent, WebcastGoalUpdateMessage):
    """GoalUpdateEvent."""


class HourlyRankEvent(BaseEvent, WebcastHourlyRankMessage):
    """HourlyRankEvent."""


class ImDeleteEvent(BaseEvent, WebcastImDeleteMessage):
    """ImDeleteEvent."""


class InRoomBannerEvent(BaseEvent, WebcastInRoomBannerMessage):
    """InRoomBannerEvent."""


class JoinEvent(BaseEvent, WebcastMemberMessage):
    """JoinEvent."""
    user: ExtendedUser
    operator: ExtendedUser


class LikeEvent(BaseEvent, WebcastLikeMessage):
    """LikeEvent."""
    user: ExtendedUser


class LinkEvent(BaseEvent, WebcastLinkMessage):
    """LinkEvent."""


class LinkLayerEvent(BaseEvent, WebcastLinkLayerMessage):
    """LinkLayerEvent."""


class LinkMicArmiesEvent(BaseEvent, WebcastLinkMicArmies):
    """LinkMicArmiesEvent."""


class LinkMicBattleEvent(BaseEvent, WebcastLinkMicBattle):
    """LinkMicBattleEvent."""


class LinkMicBattlePunishFinishEvent(BaseEvent, WebcastLinkMicBattlePunishFinish):
    """LinkMicBattlePunishFinishEvent."""


class LinkMicFanTicketMethodEvent(BaseEvent, WebcastLinkMicFanTicketMethod):
    """LinkMicFanTicketMethodEvent."""


class LinkMicMethodEvent(BaseEvent, WebcastLinkMicMethod):
    """LinkMicMethodEvent."""


class LinkmicBattleTaskEvent(BaseEvent, WebcastLinkmicBattleTaskMessage):
    """LinkmicBattleTaskEvent."""


class LiveIntroEvent(BaseEvent, WebcastLiveIntroMessage):
    """LiveIntroEvent."""
    host: ExtendedUser


class MessageDetectEvent(BaseEvent, WebcastMsgDetectMessage):
    """MessageDetectEvent."""


class OecLiveShoppingEvent(BaseEvent, WebcastOecLiveShoppingMessage):
    """OecLiveShoppingEvent."""


class PollEvent(BaseEvent, WebcastPollMessage):
    """PollEvent."""


class QuestionNewEvent(BaseEvent, WebcastQuestionNewMessage):
    """QuestionNewEvent."""


class RankTextEvent(BaseEvent, WebcastRankTextMessage):
    """RankTextEvent."""


class RankUpdateEvent(BaseEvent, WebcastRankUpdateMessage):
    """RankUpdateEvent."""


class RoomEvent(BaseEvent, WebcastRoomMessage):
    """RoomEvent."""


class RoomPinEvent(BaseEvent, WebcastRoomPinMessage):
    """RoomPinEvent."""
    operator: ExtendedUser


class RoomUserSeqEvent(BaseEvent, WebcastRoomUserSeqMessage):
    """RoomUserSeqEvent."""


class SocialEvent(BaseEvent, WebcastSocialMessage):
    """SocialEvent."""
    user: ExtendedUser


class SystemEvent(BaseEvent, WebcastSystemMessage):
    """SystemEvent."""


class UnauthorizedMemberEvent(BaseEvent, WebcastUnauthorizedMemberMessage):
    """UnauthorizedMemberEvent."""


EVENT_MAPPINGS: Dict[str, Type[BaseEvent]] = {
    "WebcastBarrageMessage": BarrageEvent,
    "WebcastCaptionMessage": CaptionEvent,
    "WebcastChatMessage": CommentEvent,
    "WebcastControlMessage": ControlEvent,
    "WebcastEmoteChatMessage": EmoteChatEvent,
    "WebcastEnvelopeMessage": EnvelopeEvent,
    "WebcastGiftMessage": GiftEvent,
    "WebcastGoalUpdateMessage": GoalUpdateEvent,
    "WebcastHourlyRankMessage": HourlyRankEvent,
    "WebcastImDeleteMessage": ImDeleteEvent,
    "WebcastInRoomBannerMessage": InRoomBannerEvent,
    "WebcastMemberMessage": JoinEvent,
    "WebcastLikeMessage": LikeEvent,
    "WebcastLinkMessage": LinkEvent,
    "WebcastLinkLayerMessage": LinkLayerEvent,
    "WebcastLinkMicArmies": LinkMicArmiesEvent,
    "WebcastLinkMicBattle": LinkMicBattleEvent,
    "WebcastLinkMicBattlePunishFinish": LinkMicBattlePunishFinishEvent,
    "WebcastLinkMicFanTicketMethod": LinkMicFanTicketMethodEvent,
    "WebcastLinkMicMethod": LinkMicMethodEvent,
    "WebcastLinkmicBattleTaskMessage": LinkmicBattleTaskEvent,
    "WebcastLiveIntroMessage": LiveIntroEvent,
    "WebcastMsgDetectMessage": MessageDetectEvent,
    "WebcastOecLiveShoppingMessage": OecLiveShoppingEvent,
    "WebcastPollMessage": PollEvent,
    "WebcastQuestionNewMessage": QuestionNewEvent,
    "WebcastRankTextMessage": RankTextEvent,
    "WebcastRankUpdateMessage": RankUpdateEvent,
    "WebcastRoomMessage": RoomEvent,
    "WebcastRoomPinMessage": RoomPinEvent,
    "WebcastRoomUserSeqMessage": RoomUserSeqEvent,
    "WebcastSocialMessage": SocialEvent,
    "WebcastSystemMessage": SystemEvent,
    "WebcastUnauthorizedMemberMessage": UnauthorizedMemberEvent,
}


ProtoEvent: Type = Union[
    BarrageEvent,
    CaptionEvent,
    CommentEvent,
    ControlEvent,
    EmoteChatEvent,
    EnvelopeEvent,
    GiftEvent,
    GoalUpdateEvent,
    HourlyRankEvent,
    ImDeleteEvent,
    InRoomBannerEvent,
    JoinEvent,
    LikeEvent,
    LinkEvent,
    LinkLayerEvent,
    LinkMicArmiesEvent,
    LinkMicBattleEvent,
    LinkMicBattlePunishFinishEvent,
    LinkMicFanTicketMethodEvent,
    LinkMicMethodEvent,
    LinkmicBattleTaskEvent,
    LiveIntroEvent,
    MessageDetectEvent,
    OecLiveShoppingEvent,
    PollEvent,
    QuestionNewEvent,
    RankTextEvent,
    RankUpdateEvent,
    RoomEvent,
    RoomPinEvent,
    RoomUserSeqEvent,
    SocialEvent,
    SystemEvent,
    UnauthorizedMemberEvent,
]


__all__ = [
    "BarrageEvent",
    "CaptionEvent",
    "CommentEvent",
    "ControlEvent",
    "EmoteChatEvent",
    "EnvelopeEvent",
    "GiftEvent",
    "GoalUpdateEvent",
    "HourlyRankEvent",
    "ImDeleteEvent",
    "InRoomBannerEvent",
    "JoinEvent",
    "LikeEvent",
    "LinkEvent",
    "LinkLayerEvent",
    "LinkMicArmiesEvent",
    "LinkMicBattleEvent",
    "LinkMicBattlePunishFinishEvent",
    "LinkMicFanTicketMethodEvent",
    "LinkMicMethodEvent",
    "LinkmicBattleTaskEvent",
    "LiveIntroEvent",
    "MessageDetectEvent",
    "OecLiveShoppingEvent",
    "PollEvent",
    "QuestionNewEvent",
    "RankTextEvent",
    "RankUpdateEvent",
    "RoomEvent",
    "RoomPinEvent",
    "RoomUserSeqEvent",
    "SocialEvent",
    "SystemEvent",
    "UnauthorizedMemberEvent",
    "EVENT_MAPPINGS",
    "ProtoEvent",
]
