# AUTOGENERATED by scripts/proto/gen_aliases.py — do not edit.
# Regenerate via: python scripts/proto/gen_aliases.py
# Source map: scripts/proto/resources/aliases.yaml
#
# This module attaches @property descriptors to existing classes via
# ``setattr``-style mutation, which mypy can't model statically.
# mypy: ignore-errors

from TikTokLiveProto.v3.webcast.shared.message import BaseProtoMessage as ProtoMessageFetchResultBaseProtoMessage
from TikTokLive.proto.custom_proto import ExtendedUser as _ExtendedUser
from TikTokLive.proto.custom_proto import ExtendedGift as _ExtendedGift


def _legacy_alias(target_attr: str, doc: str | None = None) -> property:
    """Build a read-only @property that delegates to ``target_attr``."""

    def _get(self):
        return getattr(self, target_attr)

    p = property(_get)
    if doc:
        p.__doc__ = doc
    return p


_ExtendedUser.username = _legacy_alias("display_id", "Legacy alias; v3 exposes this field as ``display_id``.")
_ExtendedUser.nick_name = _legacy_alias("nickname", "Legacy alias; v3 exposes this field as ``nickname``.")
_ExtendedUser.badges = _legacy_alias("badge_list", "v2 alias; v3 reverted this field to ``badge_list``.")
_ExtendedGift.gift_type = _legacy_alias("type", "Legacy alias; v2 renamed ``type`` to ``gift_type``, v3 reverted.")
_ExtendedGift.gift_name = _legacy_alias("name", "v2 alias; v3 reverted this field to ``name``.")
_ExtendedGift.gift_image = _legacy_alias("image", "v2 alias; v3 reverted this field to ``image``.")


__all__ = [
    "ProtoMessageFetchResultBaseProtoMessage",
]
