# AUTOGENERATED by scripts/proto/gen_aliases.py — do not edit.
# Regenerate via: python scripts/proto/gen_aliases.py
# Source map: scripts/proto/resources/aliases.yaml

from TikTokLiveProto.generated.v2 import BaseProtoMessage as ProtoMessageFetchResultBaseProtoMessage
from TikTokLive.proto.custom_proto import ExtendedUser as _ExtendedUser
from TikTokLive.proto.custom_proto import ExtendedGift as _ExtendedGift


def _legacy_alias(target_attr: str, doc: str | None = None) -> property:
    """Build a read-only @property that delegates to ``target_attr``."""

    def _get(self):
        return getattr(self, target_attr)

    p = property(_get)
    if doc:
        p.__doc__ = doc
    return p


_ExtendedUser.username = _legacy_alias("unique_id", "Legacy alias; v2 renamed this field to ``unique_id``.")
_ExtendedUser.nick_name = _legacy_alias("nickname", "Legacy alias; v2 renamed this field to ``nickname``.")
_ExtendedUser.badge_list = _legacy_alias("badges", "Legacy alias; v2 renamed this field to ``badges``.")
_ExtendedGift.name = _legacy_alias("gift_name", "Legacy alias; v2 renamed this field to ``gift_name``.")
_ExtendedGift.type = _legacy_alias("gift_type", "Legacy alias; v2 renamed this field to ``gift_type``.")
_ExtendedGift.image = _legacy_alias("gift_image", "Legacy alias; v2 renamed this field to ``gift_image``.")


__all__ = [
    "ProtoMessageFetchResultBaseProtoMessage",
]
